<?php
//module/Album/view/album/auth/login.phtml
$form = $this->form;
$form->setAttribute('action', $this->url(
    'login/process',
    array(
        'action'     => 'authenticate',
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('username')) . '<br>';
echo $this->formRow($form->get('password')) . '<br>';
echo $this->formRow($form->get('rememberme')) . '<br>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
        echo '<li>'.$message.'</li>';
    }
    echo '</ul>';
}