<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete album';
$this->headTitle($title);

$url = $this->url('album', array(
    'action' => 'delete',
    'id' => $this->id,
));
?>
<div class="mdl-card mdl-shadow--16dp centre_card">
    <div class="mdl-card__supporting-text">
        <p>Are you sure that you want to delete
            '<?php echo $this->escapeHtml($album->title); ?>' by
            '<?php echo $this->escapeHtml($album->artist); ?>'?
        </p>

        <form action="<?php echo $url; ?>" method="post">

            <input type="hidden" name="id" value="<?php echo (int)$album->id; ?>"/>
            <button class="mdl-button mdl-js-button mdl-js-ripple-effect submit-button" name="del" value="Yes" type="submit">
                OUI
            </button>
            <button class="mdl-button mdl-js-button mdl-js-ripple-effect submit-button" name="del" value="No" type="submit">
                NON
            </button>
        </form>
    </div>
</div>