<?php
// module/Album/view/album/album/index.phtml:

$title = 'Mes albums';
$this->headTitle($title);
?>

<div class="table-album">

    <div class="fab">
        <a href="<?php echo $this->url('album', array('action' => 'add')); ?>">
            <button
                class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored mdl-js-ripple-effect mdl-button--mini-fab">
                <i class="material-icons">add</i>
            </button>
        </a>
    </div>

    <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
        <thead>
        <tr>
            <th class="mdl-data-table__cell--non-numeric">Title</th>
            <th class="mdl-data-table__cell--non-numeric">Artist</th>
            <th class="mdl-data-table__cell--non-numeric">&nbsp;</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($albums as $album) : ?>
            <tr>
                <td class="mdl-data-table__cell--non-numeric"><?php echo $this->escapeHtml($album->title); ?></td>
                <td class="mdl-data-table__cell--non-numeric"><?php echo $this->escapeHtml($album->artist); ?></td>
                <td class="mdl-data-table__cell--non-numeric">
                    <a href="<?php echo $this->url('album',
                        array('action' => 'edit', 'id' => $album->id)); ?>"><i class="material-icons">edit</i></a>
                    <a href="<?php echo $this->url('album',
                        array('action' => 'delete', 'id' => $album->id)); ?>"><i class="material-icons">delete</i></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>


